class Survey < ActiveRecord::Base

  SKILLS = [
            [:coach_ability, 
             "willingness  to learn and share the coaching process."],
            [:athletes_knowledge, 
             "Ability to understand sports specific Information"],
            [:technical_competency, 
             "skill acquisition ability to technically change things."],
            [:physical_conditioning, 
             "Aerobic, overall general fitness"],
            [:strength, 
             "The extent to which muscles can exert force by contracting against resistance, Skill and strength ability to hold specific movements"],
            [:power, 
             "The ability to exert maximum muscular contraction instantly in an explosive burst of movements (Jumping or sprint starting)"],
            [:agility, 
             "The ability to perform a series of explosive power movements in rapid succession in opposing directions (ZigZag running or cutting movements)"],
            [:balance, 
             "The ability to control the body's position, either stationary (e.g. a handstand) or while moving (e.g. a gymnastics stunt)"],
            [:team_work, 
             "Ability to work with a team or partner"],
            [:sustainable_power, 
             "Ability to hold a high power over 3 minutes"],
            [:confidence, 
             "confidence in what you do as a person."],
            [:time_management, 
             "Getting the best from the time available."],
            [:communication, 
             "good  communication with your  support team to allow engagement in all areas of  life that will allow  you to enjoy and reach  your goals as a athlete. "],
            [:motivation, 
             "Enjoys the challenge, accepts the task, and has the patience to to understance the time necessary for reaching full potential "],
            [:health_managment, 
             "Understanding what is best practise (hygiene, injury, and illness)"],
            [:nutrition, 
             "Understanding the requirements of a young growing developing athlete in a your sport"],
            [:recovery, 
             "Understanding the importance of recovery as a factor of your development"],
            [:flexibility, 
             "The ability to achieve an extended range of motion without being impeded by excess tissue, i.e. fat or muscle (Executing a leg split)"],
            [:local_muscle_endurance, 
             "A single muscle's ability to perform sustained work (Rowing or cycling)"],
            [:cardiovascular_endurance, 
             "The heart's ability to deliver blood to working muscles and their ability to use it (Running long distances)"],
            [:strength_endurance, 
             "A muscle's ability to perform a maximum contracture time after time (Continuous explosive rebounding through an entire basketball game)"],
            [:coordination, 
             " The ability to integrate the above listed components so that effective movements are achieved"],
            [:psychological_skills, 
             "amplication of error, goal setting, Imagerie, Positive approach, be able to take critiscism"],
  ]

end
